# NumPy Assignment

## Ques1

In [2]:
import numpy as np

In [6]:
array1= np.zeros((1,10))

In [7]:
print(array1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
array2= np.ones((1,10))

In [10]:
print(array2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [30]:
array3=np.ones((1,10))*5

In [31]:
print(array3)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [32]:
array=np.array((array1,array2,array3))

In [33]:
print(array)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]]


## ques 2

In [37]:
n=np.array(range(30,71,2))
print(n)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


## ques 3

In [12]:
array=np.ones((10,10))
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [13]:
array[1:-1,1:-1]=0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## ques 4

In [39]:
array=np.array(range(12,38))
print(array)
print(np.flip(array))

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


## ques 5

In [15]:
array1=np.array([0,10,20,40,60])
array2=np.array([10,30,40])
def merge(array1,array2):
    for i in array1{
        if i in array2= True
        print array1[i]}          ##### not working 

SyntaxError: invalid syntax (<ipython-input-15-211bc615fec2>, line 4)

# or

In [53]:
array1=np.array([0,10,20,40,60])
array2=np.array([10,30,40])
print(np.intersect1d(array1,array2))

[10 40]


## ques 6

In [16]:
array=np.array(range(11,21))
print(array)
np.shape(array)

[11 12 13 14 15 16 17 18 19 20]


(10,)

In [17]:
array2=np.reshape(array,(2,5))
print(array2)  ### new shape

[[11 12 13 14 15]
 [16 17 18 19 20]]


## ques 7

In [19]:
list=[[[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]]
array=np.array(list)
array

array([[[ 0,  1,  3],
        [ 5,  7,  9]],

       [[ 0,  2,  4],
        [ 6,  8, 10]]])

In [22]:
array1=np.reshape(array,(2,-1))
array1   ####### output not as desired 
# we want [[ 0 1 3 0 2 4]
###       [ 5 7 9 6 8 10]]

array([[ 0,  1,  3,  5,  7,  9],
       [ 0,  2,  4,  6,  8, 10]])

In [25]:
array2=np.hstack(array)   ####correct way
print(array2)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


## ques 8

In [26]:
array=np.arange(1,15,1)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [120]:
np.split(array,(2,4))  ### unable to break into 3 arrays of different sizes.. i.e.2,4,8

[array([1, 2]), array([3, 4]), array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])]

In [28]:
array2=np.split(np.split(array,(2,2)),(2,2)) #### tried nested split.. not working
print(array2)

[array([array([1, 2]), array([], dtype=int32)], dtype=object), array([], dtype=object), array([array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])],
      dtype=object)]


## ques 9

In [128]:
array=np.arange(0,39,2)
array
len(array)

20

In [129]:
array2=np.reshape(array,(5,4))
array2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])

In [133]:
array3=np.reshape(array2,20)
array3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

# or

In [134]:
array3=np.reshape(array2,-1)
array3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

## ques 10

In [154]:
array=np.arange(0,20).reshape(4,5)
array1=array.copy
print(array1)

<built-in method copy of numpy.ndarray object at 0x0000013CD1462940>


In [151]:
array[:,0]=array[:,3]
array

array([[ 3,  1,  2,  3,  4],
       [ 8,  6,  7,  8,  9],
       [13, 11, 12, 13, 14],
       [18, 16, 17, 18, 19]])

In [152]:
array[:,3]=array1[:,0]
array

array([[ 3,  1,  2,  3,  4],
       [ 8,  6,  7,  8,  9],
       [13, 11, 12, 13, 14],
       [18, 16, 17, 18, 19]])

# or

In [155]:
array=np.arange(0,20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [156]:
array[:,[0,3]]=array[:,[3,0]]
array

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])